version: "3.4"
services:
  weaviate:
    image: semitechnologies/weaviate:1.33.0-rc.1-109e041
    container_name: weaviate
    ports:
      - "8090:8080"  
      - "50052:50051"
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"    
      - --scheme
      - http
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
      AUTOSCHEMA_ENABLED: 'true'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

volumes:
  weaviate_data:
